version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    container_name: nginx-proxy
    networks:
      - front
    ports:
      - "80:80"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx-log:/var/log/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/htpasswd:/etc/nginx/htpasswd
      - ./config/nginx/nginx_proxy.conf:/etc/nginx/conf.d/nginx_proxy.conf:ro

networks:
  front:
    external: true
